version: "3.9"
services:
  db:
    container_name: db-c2_666usm
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: c2_666usm_db
      MYSQL_USER: c2666
      MYSQL_PASSWORD: 123456
    networks:
      - net-c2666usm
  web:
    container_name: web-c2666usm
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-c2666usm
networks:
  net-c2666usm:
    
